<%--
  Created by IntelliJ IDEA.
  User: Administrator
  Date: 2021/7/7
  Time: 0:13
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>PlantEMS-links</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Plant Epigenetic Modification Sites database"/>
    <meta name="keywords" content="Plant Epigenetic Modification Sites database"/>
    <meta name="author" content="lin-group"/>

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700" rel="stylesheet">

    <%@include file="/pages/common/header.jsp" %>

</head>
<body>

<div class="fh5co-loader"></div>

<div id="page">
    <!--     <div id="line" style = "width: 1170px; height: 5px; background: #33cccc;margin: 0 auto;"></div> -->
    <%@include file="/pages/common/navigator_links.jsp" %>


    <div id="fh5co-counter" class="fh5co-counters" style="width:1170px; margin:0 auto;"
         data-stellar-background-ratio="0.5">
        <div class="overlay" style="width: 1170px;margin: 0 auto">

            <!--             <p style="font-size: 18px">PlantEMS (Plant Epigenetic Modification Sites) Database  is an integrative database for storing, analyzing and visualizing of DNA 6mA and 4mC methylation in Rosaceae. It provides a user-friendly interface to host, browse, search and download 6mA and 4mC profiles and also offers a genome browse to visualize DNA methylation sites and related coverage and gene annotation. The MDR will become a powerful tool to provide a genome-wide view of DNA 6mA and 4mC methylation in Rosaceae. is an integrative database for storing, analyzing and visualizing of DNA 6mA and 4mC methylation in Rosaceae. It provides a user-friendly interface to host, browse, search and download 6mA and 4mC profiles and also offers a genome browse to visualize DNA methylation sites and related coverage and gene annotation. The MDR will become a powerful tool to provide a genome-wide view of DNA 6mA and 4mC methylation in Rosaceae.</p> -->
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1" style="margin-top: -90px">
                    <div class="row">
                        <br>
                        <h2 style="color: #fafcfc"><span style="color: #f39800;font-weight:bold;"> DNA modification-related databases</span>
                        </h2>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">1)<a
                                href="http://sysbio.sysu.edu.cn/methsmrt/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> MethSMRT:</span></a> <a
                                style="color:#fafcfc;">an integrative database for DNA N6-methyladenine and
                            N4-methylcytosine generated by single-molecular real-time sequencing.</a></p>

                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">2)<a
                                href="http://bioinfo2.ugr.es/NGSmethDB" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> NGSmethDB 2017:</span></a> <a
                                style="color:#fafcfc;">enhanced methylomes and differential methylation.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">3)<a
                                href="http://bigd.big.ac.cn/methbank" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> MethBank 3.0:</span></a> <a
                                style="color:#fafcfc;">a database of DNA methylomes across a variety of species</a></p>
                        <!-- <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc;">3)<a href="http://bigd.big.ac.cn/methbank" style="color: #f39800;"><span style="border-bottom:dashed #000000 1px;"> MethBank 3.0:</span></a> <a style="color:#fafcfc;">a database of DNA methylomes across a variety of species.<a/></p> -->
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">4)<a href="http://mdr.xieslab.org"
                                                                                          style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> MDR:</span></a><a style="color:#fafcfc;">an
                            integrative DNA N6-methyladenine and N4-methylcytosine modification database for
                            Rosaceae.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">5)<a
                                href="https://dnamod.hoffmanlab.org/index.html" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> DNAmod:</span></a> <a style="color:#fafcfc;">the
                            DNA modification database.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">6)<a
                                href="http://www.elabcaas.cn/rice/index.html" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> eRice:</span></a> <a style="color:#fafcfc;">a
                            refined epigenomic platform for japonica and indica rice.</a></p>
                        <br>
                        <!-- RNA modification-related databases -->
                        <h2 style="color: #fafcfc"><span style="color: #f39800;font-weight:bold;"> RNA modification-related databases</span>
                        </h2>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">1)<a
                                href="http://m6avar.renlab.org" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> m6AVar:</span></a> <a style="color:#fafcfc;">a
                            database of functional variants involved in m6A modification.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">2)<a
                                href="http://www.biosequencing.cn/PRMdb/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> PRMdb:</span></a> <a style="color:#fafcfc;">A
                            repository of predicted RNA modifications in plants.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">3)<a
                                href="http://modomics.genesilico.pl" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> MODOMICS:</span></a> <a
                                style="color:#fafcfc;">a database of RNA modification pathways. 2017 update.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">4)<a
                                href="http://srv00.recas.ba.infn.it/redidb/index.html" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> REDIdb 3.0:</span></a> <a
                                style="color:#fafcfc;">a comprehensive collection of RNA editing events in plant
                            organellar genomes.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">5)<a
                                href="https://bioinformatics.sc.cn/RNAmod/index.php" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> RNAmod:</span></a> <a style="color:#fafcfc;">an
                            integrated system for the annotation of mRNA modifications.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">6)<a href="http://rmvar.renlab.org"
                                                                                          style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> RMVar:</span></a> <a style="color:#fafcfc;">an
                            updated database of functional variants involved in RNA modifications.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">7)<a
                                href="http://180.208.58.66/m6A-Atlas/index.html" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> m6A-Atlas:</span></a> <a
                                style="color:#fafcfc;">a comprehensive knowledgebase for unraveling the
                            N6-methyladenosine (m6A) epitranscriptome.</a></p>
                        <br>
                        <!--  PTM-related databases -->
                        <h2 style="color: #fafcfc"><span
                                style="color: #f39800;font-weight:bold;"> PTM-related databases</span></h2>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">1)<a
                                href="http://phossnp.biocuckoo.org/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> PhosSNP:</span></a> <a
                                style="color:#fafcfc;">PhosSNP for systematic analysis of genetic polymorphisms that
                            influence protein phosphorylation.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">2)<a
                                href="http://phosphat.uni-hohenheim.de/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> PhosPhAt:</span></a> <a
                                style="color:#fafcfc;">the Arabidopsis thaliana phosphorylation site database. An
                            update.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">3)<a
                                href="http://dbSNO.mbc.nctu.edu.tw" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> dbSNO 2.0:</span></a> <a
                                style="color:#fafcfc;">a resource for exploring structural environment, functional and
                            disease association and regulatory network of protein S-nitrosylation.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">4)<a
                                href="http://dbpaf.biocuckoo.org/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> dbPAF:</span></a> <a style="color:#fafcfc;">an
                            integrative database of protein phosphorylation in animals and fungi.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">5)<a
                                href="http://ptmd.biocuckoo.org/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> PTMD:</span></a> <a style="color:#fafcfc;">a
                            database of human disease-associated post-translational modifications.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">6)<a
                                href="http://plmd.biocuckoo.org/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> PLMD:</span></a> <a style="color:#fafcfc;">an
                            updated data resource of protein lysine modifications.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">7)<a
                                href="http://www.psb.ugent.be/PlantPTMViewer" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> Plant PTM Viewer:</span></a> <a
                                style="color:#fafcfc;">the Plant PTM Viewer, a central resource for exploring plant
                            protein modifications.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">8)<a
                                href="http://dbPTM.mbc.nctu.edu.tw/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> dbPTM in 2019:</span></a> <a
                                style="color:#fafcfc;">exploring disease association and cross-talk of
                            post-translational modifications.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">9)<a
                                href="http://vptmdb.com:8787/VPTMdb/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> VPTMdb:</span></a> <a style="color:#fafcfc;">a
                            viral posttranslational modification database.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">10)<a
                                href="http://epsd.biocuckoo.cn/" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> EPSD:</span></a> <a style="color:#fafcfc;">a
                            well-annotated database of protein phosphorylation sites in eukaryotes.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">11)<a
                                href="http://dbpsp.biocuckoo.cn" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> dbPSP 2.0:</span></a> <a
                                style="color:#fafcfc;">an updated database of protein phosphorylation sites in
                            prokaryotes.</a></p>
                        <p style="font: 18px Arial, Arial, Sans-Serif;color:#fafcfc">12)<a
                                href="http://icysmod.omicsbio.info/index.php" style="color: #f39800;"><span
                                style="border-bottom:dashed #000000 1px;"> iCysMod:</span></a> <a
                                style="color:#fafcfc;">an integrative database for protein cysteine modifications in
                            eukaryotes.</a></p>

                    </div>
                </div>
            </div>
        </div>
    </div>


    <footer id="fh5co-footer" role="contentinfo" style="width: 1158px; margin: 0 auto;padding: 0 10px 10px 10px">
        <!-- <div class="overlay"></div> -->

        <div class="row copyright" style=" padding: 20px 0px 7px 0px;">
            <div class="col-md-12 text-center">
                <p>
                    <small class="block" style="padding:0;font-size: 113%">&copy; Copyright LinGroup(lin-group.cn) @
                        2021 All rights reservedÂ© Copyright.</small>
                    <!-- 					<small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash</a> &amp; <a href="https://www.pexels.com/" target="_blank">Pexels</a></small> -->
                </p>
            </div>
        </div>
    </footer>
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>

<script>
    $(function () {
        $('#colour-variations ul').styleSwitcher({
            defaultThemeId: 'theme-switch',
            hasPreview: false,
            cookie: {
                expires: 30,
                isManagingLoad: true
            }
        });
        $('.option-toggle').click(function () {
            $('#colour-variations').toggleClass('sleep');
        });
    });
</script>
<!-- End demo purposes only -->
</body>
</html>


